version: '2'
services:
    momentstasks-app:
        image: momentstasks
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://momentstasks-mysql:3306/momentstasks?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8089:8089
    momentstasks-mysql:
        extends:
            file: mysql.yml
            service: momentstasks-mysql
